spring:
  application:
    name: stg-Test-App
  datasource:
    url: jdbc:mysql://localhost:3306/stg_database
    username: Root
    password: Passwort
    driver-class-name: Com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: Aktualisieren
    show-sql: true
    properties:
      hibernate:
        dialect: Org.Hibernate.dialect.MySQL8Dialect
